# Generated by Django 5.0.4 on 2024-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pets',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
