# Generated by Django 5.0.4 on 2024-05-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpm', '0003_breed_owner_pet_species_delete_pets_owner_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
    ]
